# Node docker image on which this would be run
image: node:12.10.0

#This command is run before actual stages start running
before_script:
  - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
  - npm install

stages:
  - deploy

deployToAWS:
  only:
    - master
  stage: deploy
  script:
    - bash deploy/deploy.sh
